# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.1
  - 7.2

# Commands to be run before your environment runs.
before_script:
  - composer self-update
 
# Customize when the notification emails are sent.
notifications:
Â email: lablnet01@gmail.com
